
name: Docker Workflow

on: [pull_request,workflow_dispatch,push]

env:
  UNSTABLE_IMG: ghcr.io/${{ github.repository_owner }}/pliers:unstable
  EXEC_IMG: ghcr.io/${{ github.repository_owner }}/ci:ci_exec
  BUILDER_IMG: ghcr.io/${{ github.repository_owner }}/ci:ci_build
  DOC_IMG: ghcr.io/${{ github.repository_owner }}/ci:ci_docs
  TEST_IMG: ghcr.io/${{ github.repository_owner }}/ci:ci_test
  

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Build the base image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        target: builder
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        cache-from: |
          type=registry,ref=${{ env.BUILDER_IMG }}
        load: true
        tags: ${{ env.BUILDER_IMG }}
    - 
      name: Build Executable Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        target: executable
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        cache-from: |
          type=registry,ref=${{ env.UNSTABLE_IMG }}
        load: true
        tags: |
          ${{ env.EXEC_IMG }}
          ${{ env.UNSTABLE_IMG }}
    - 
      name: Build Testing Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        target: tests
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        cache-from: |
          type=docker,ref=${{ env.EXEC_IMG }}
        load: true
        tags: |
          ${{ env.TEST_IMG }}
    -
      name: run tests
      run: docker run ${TEST_IMG}
    -
      name: Push to registry (if not pull request)
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
      run: |
        if [ "${GITHUB_EVENT_NAME}" == "push" ] && [ ! -z "${CR_PAT}" ]; then
          echo "${CR_PAT}" | docker login ghcr.io -u USERNAME --password-stdin 
          docker push ${UNSTABLE_IMG}  # push image for users
          docker push ${BUILDER_IMG}  # push image for build cache 
          # check if this is a release
          ref_name=${GITHUB_REF##*/}
          if [[ "${ref_name}" == v* ]]; then
            release=${UNSTABLE_IMG/unstable/${ref_name}}
            docker tag ${UNSTABLE_IMG} ${release}
            docker push ${release}
          fi
        else
          echo "pull request, not pushing"
        fi