
name: Pull Request Docker Check

on: [pull_request,workflow_dispatch,push]

env:
  UNSTABLE_IMG: ghcr.io/jdkent/pliers:unstable
  EXEC_IMG: ghcr.io/jdkent/pliers:exec
  BUILDER_IMG: ghcr.io/jdkent/pliers:build
  DOC_IMG: ghcr.io/jdkent/pliers:docs
  REGISTRY_PATH: /tmp/registry
  CACHE_PATH: /tmp/.buildx-cache
  

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Build and export builder
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        target: builder
        cache-from: |
          type=registry,ref=${{ env.BUILDER_IMG }}
          type=registry,ref=${{ env.UNSTABLE_IMG }}
        cache-to: |
          type=registry,ref=${{ env.BUILDER_IMG }},mode=max
        push: true
        tags: ${{ env.BUILDER_IMG }}
    - 
      name: Build and export executable
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        target: executable
        cache-from: |
          type=registry,ref=${{ env.EXEC_IMG }}
        cache-to: |
          type=registry,ref=${{ env.EXEC_IMG }},mode=max
        push: true
        tags: ${{ env.EXEC_IMG }}

  docs:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    # - 
    #   name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   timeout-minutes: 30
    - 
      name: Build and export
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        target: docs
        push: true
        tags: ${{ env.DOC_IMG }}
        cache-from: |
          type=registry,ref=${{ env.BUILDER_IMG }}
          type=registry,ref=${{ env.EXEC_IMG }}
          type=registry,ref=${{ env.DOC_IMG }}
          type=registry,ref=${{ env.UNSTABLE_IMG }}
        cache-to: |
          type=registry,ref=${{ env.DOC_IMG }}
    # - 
    #   name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   timeout-minutes: 30
    -
      name: run doc tests
      run: docker run ${DOC_IMG}
    
