
name: Pull Request Docker Check

on: [pull_request,workflow_dispatch,push]

env:
  UNSTABLE_IMG: jdkent/pliers:unstable
  EXEC_IMG: ghcr.io/jdkent/ci:ci_exec
  BUILDER_IMG: ghcr.io/jdkent/ci:ci_build
  DOC_IMG: ghcr.io/jdkent/ci:ci_docs
  TEST_IMG: ghcr.io/jdkent/ci:ci_test
  

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Build and export builder
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        target: builder
        cache-from: |
          type=registry,ref=${{ env.BUILDER_IMG }}
          type=registry,ref=${{ env.UNSTABLE_IMG }}
        cache-to: |
          type=registry,ref=${{ env.BUILDER_IMG }},mode=max
        push: true
        tags: ${{ env.BUILDER_IMG }}
    - 
      name: Build and export executable
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        target: executable
        cache-from: |
          type=registry,ref=${{ env.EXEC_IMG }}
        cache-to: |
          type=registry,ref=${{ env.EXEC_IMG }},mode=max
        push: true
        tags: |
          ${{ env.EXEC_IMG }}
          ${{ env.EXEC_IMG }}_${{ github.sha }}

  docs:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    # - 
    #   name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   timeout-minutes: 30
    - 
      name: Build and export
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        target: docs
        load: true
        tags: ${{ env.DOC_IMG }}
        cache-from: |
          type=registry,ref=${{ env.BUILDER_IMG }}
          type=registry,ref=${{ env.EXEC_IMG }}
          type=registry,ref=${{ env.DOC_IMG }}
        cache-to: |
          type=registry,ref=${{ env.DOC_IMG }}
    # - 
    #   name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   timeout-minutes: 30
    -
      name: run doc tests
      run: docker run ${DOC_IMG}
    - 
      name: push docs image
      run: docker push ${DOC_IMG}
    
  push:
    if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags'))
    runs-on: ubuntu-latest
    needs:
      - build_image
      - docs
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: rename image to jdkent/pliers
        run: |
          docker pull ${{ env.EXEC_IMG }}_${{ github.sha }}
          docker tag ${{ env.EXEC_IMG }}_${{ github.sha }} jdkent/pliers:unstable
          docker push jdkent/pliers:unstable
          if ${GITHUB_REF##*/} != 'main':
            docker tag ${{ env.EXEC_IMG }}_${{ github.sha }} jdkent/pliers:${GITHUB_REF##*/}
            docker push jdkent/pliers:${GITHUB_REF##*/}
  clean:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - build_image
      - docs
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: delete old images
        uses: smartsquaregmbh/delete-old-packages@v0.2.0
        with:
          keep: 5
          names: ci