
name: Pull Request Docker Check

on: [pull_request,workflow_dispatch,push]

env:
  IMAGE_NAME: localhost:5000/pliers:ci
  REGISTRY_PATH: /tmp/registry
  CACHE_PATH: /tmp/.buildx-cache

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    -
      name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: |
          /tmp/registry
          /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - 
      name: Start Docker registry
      run: |
        docker run -d -p 5000:5000 -v ${REGISTRY_PATH}:/var/lib/registry --name registry registry:2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host
    - 
      name: Rename builder image
      run: |
        set +e
            docker pull localhost:5000/python:3.7-slim
            success=$?
            set -e
            if [[ "$success" = "0" ]]; then
                echo "Pulling from local registry"
                docker tag localhost:5000/python:3.7-slim python:3.7-slim
            else
                echo "Pulling from Docker Hub"
                docker pull python:3.7-slim
                docker tag python:3.7-slim localhost:5000/python:3.7-slim
                docker push localhost:5000/python:3.7-slim
            fi
    - 
      name: Build and export build stage
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        target: builder
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        cache-from: type=local,src=${{ env.CACHE_PATH }}
        cache-to: type=local,dest=${{ env.CACHE_PATH }}-new
        push: true
        tags: localhost:5000/pliers-builder:ci
    - 
      name: Build and export executable
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        target: executable
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        cache-from: |
          type=local,src=${{ env.CACHE_PATH }}
        cache-to: type=local,dest=${{ env.CACHE_PATH }}-new
        push: true
        tags: ${{ env.IMAGE_NAME }}
    - 
      name: Build and export doctest
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        target: doctest
        cache-from: |
          type=local,src=${{ env.CACHE_PATH }}
        cache-to: type=local,dest=${{ env.CACHE_PATH }}-new
        push: true
        tags: localhost:5000/pliers-doctest:ci
    - 
      name: display images
      run: |
        docker images
    - 
      name: Stop Docker registry
      run: docker stop registry
    -
      name: Upload Docker registry data for testing
      uses: actions/upload-artifact@v2
      with:
        name: docker-registry-data
        path: /tmp/registry
    -
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  doctest:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Download Docker registry data from build job
      uses: actions/download-artifact@v2
      with:
        name: docker-registry-data
        path: /tmp/registry
    - 
      name: Start Docker registry
      run: |
        docker run -d -p 5000:5000 -v ${REGISTRY_PATH}:/var/lib/registry --name registry registry:2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host
    - 
      name: Import Docker images
      run: |
        docker pull localhost:5000/pliers-doctest:ci
        docker pull localhost:5000/pliers-builder:ci
        docker pull localhost:5000/pliers:ci
    - 
      name: display images
      run: |
        docker images
    - 
      name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 30
    - 
      name: Build and export
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        tags: localhost:5000/pliers-doctest:dev
        target: doctest
        load: true
        cache-from: |
          localhost:5000/pliers-builder:ci
          localhost:5000/pliers:ci
    - 
      name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 30
    -
      name: run doctests
      run: docker run localhost:5000/pliers-doctest:ci
    - 
      name: Stop Docker registry
      run: docker stop registry

    
