
name: Docker Workflow

on: [pull_request,workflow_dispatch,push]

jobs:
  docker_test_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Set environment variables
      run: |
        repo_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
        echo ::set-env name=UNSTABLE_IMG::ghcr.io/${repo_owner}/pliers:unstable
        echo ::set-env name=EXEC_IMG::ghcr.io/${repo_owner}/pliersci:ci_exec
        echo ::set-env name=BUILDER_IMG::ghcr.io/${repo_owner}/pliersci:ci_build
        echo ::set-env name=DOC_IMG::ghcr.io/${repo_owner}/pliersci:ci_docs
        echo ::set-env name=TEST_IMG::ghcr.io/${repo_owner}/pliersci:ci_docs

    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Build the base image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        target: builder
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        cache-from: |
          type=registry,ref=${{ env.BUILDER_IMG }}
        load: true
        tags: ${{ env.BUILDER_IMG }}
    - 
      name: Build executable image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        target: executable
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        cache-from: |
          type=registry,ref=${{ env.UNSTABLE_IMG }}
        load: true
        tags: |
          ${{ env.EXEC_IMG }}
          ${{ env.UNSTABLE_IMG }}
    - 
      name: Build testing image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        target: tests
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        cache-from: |
          type=docker,ref=${{ env.EXEC_IMG }}
        load: true
        tags: |
          ${{ env.TEST_IMG }}
    -
      name: run tests
      run: docker run ${TEST_IMG}
    -
      name: Push to registry (if not pull request)
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
      run: |
        if [ "${GITHUB_EVENT_NAME}" == "push" ] && [ ! -z "${CR_PAT}" ]; then
          echo "${CR_PAT}" | docker login ghcr.io -u USERNAME --password-stdin 
          docker push ${UNSTABLE_IMG}  # push image for users
          docker push ${BUILDER_IMG}  # push image for build cache 
          # check if this is a release
          ref_name=${GITHUB_REF##*/}
          if [[ "${ref_name}" == v* ]]; then
            release=${UNSTABLE_IMG/unstable/${ref_name}}
            docker tag ${UNSTABLE_IMG} ${release}
            docker push ${release}
          fi
        else
          echo "pull request, not pushing"
        fi